export const userTestimonialsArray=[
    {name:"Bennett",
    comment:"Nam sollicitudin dignissim nunc, cursus ullamcorper eros vulputate sed. Vestibulum sit amet tortor sit amet libero lobortis semper at et odio. In eu tellus tellus. Pellentesque ullamcorper aliquet ultrices.",
    image:"/public/image/UserImage/photo_2025-11-08_21-20-03.jpg"},
    {name:"Anderson",
    comment:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    image:"/public/image/UserImage/photo_2025-11-08_21-18-59.jpg"},
    {name:"Colemen",
    comment:"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image:"/public/image/UserImage/photo_2025-11-08_21-19-03.jpg"},
    {name:"Mitchell",
    comment:"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    image:"/public/image/UserImage/photo_2025-11-08_21-19-06.jpg"},
    {name:"Morgan",
    comment:"Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image:"/public/image/UserImage/photo_2025-11-08_21-20-06.jpg"},
    {name:"Harrison",
    comment:"Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra.",
    image:"/public/image/UserImage/photo_2025-11-08_21-19-08.jpg"},
]